# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('especie', models.CharField(max_length=40)),
                ('imatge', models.ImageField(upload_to='../media/Imatges/')),
                ('poder_arma', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=5000)),
                ('altres_noms', models.CharField(blank=True, max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_mitologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicacio.Mitologia')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=1500)),
                ('resposta', models.CharField(max_length=150)),
                ('opcio1', models.CharField(max_length=150)),
                ('opcio2', models.CharField(max_length=150)),
                ('opcio3', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('actiu', models.BooleanField(default=False)),
                ('id_personatge', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Publicacio.Personatge')),
            ],
        ),
        migrations.AddField(
            model_name='preguntes',
            name='id_test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Publicacio.Test'),
        ),
    ]
