# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicacio', '0002_auto_20190523_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatge',
            name='poder_arma',
            field=models.CharField(max_length=200),
        ),
    ]
