# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicacio', '0003_auto_20190528_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personatge',
            name='poder_arma',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
